### ISSUE TITLE
Improve error handling for environment information check

### ISSUE THREAD

**Issue by edermi** [nray-scanner/nray#8]
On Citrix, gathering environment information fails and the scanner therefore refuses to start.
The function collecting the information needs proper error handling to deal with such environments.

https://github.com/nray-scanner/nray/blob/2aedc1fcec8e204c909fc79103ead3c054ac7c1e/core/scannernode.go#L188

**Comment by edermi** [comment]
Stacktrace:

~~~
time="2019-09-04T10:32:08+02:00" level=info msg="Connecting to: tcp://localhost:8601" module=core.messageQueue src=InitServerConnection
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/nray-scanner/nray/core.gatherEnvironmentInformation(0x0)
        /home/eder/code/nray-scanner/nray/core/scannernode.go:197 +0x3e8
github.com/nray-scanner/nray/core.generateNodeRegister(0x0, 0x0, 0x0, 0x2108421084, 0x37, 0x8)
        /home/eder/code/nray-scanner/nray/core/messageStuff.go:213 +0x21a
github.com/nray-scanner/nray/core.registerNode(0xe88920, 0xc0001a6d80, 0x0, 0x0, 0xc000000000, 0xe88920, 0xc0001a6d80, 0x0, 0x0, 0xc0004161e0)
        /home/eder/code/nray-scanner/nray/core/messageStuff.go:249 +0x54
github.com/nray-scanner/nray/core.RunNode(0xc00008a0a0, 0x9, 0xc00008a0c8, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/eder/code/nray-scanner/nray/core/scannernode.go:81 +0x1e8
github.com/nray-scanner/nray/cmd.glob..func1(0x14411a0, 0xc0001a3080, 0x0, 0x4)
        /home/eder/code/nray-scanner/nray/cmd/node.go:16 +0x54
github.com/spf13/cobra.(*Command).execute(0x14411a0, 0xc0001a3000, 0x4, 0x4, 0x14411a0, 0xc0001a3000)
        /home/eder/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2b5
github.com/spf13/cobra.(*Command).ExecuteC(0x1441420, 0x29, 0x0, 0x0)
        /home/eder/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x303
github.com/spf13/cobra.(*Command).Execute(...)
        /home/eder/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/nray-scanner/nray/cmd.Execute()
        /home/eder/code/nray-scanner/nray/cmd/root.go:54 +0x39
main.main()
        /home/eder/code/nray-scanner/nray/nray.go:17 +0x9a
~~~

**Comment by edermi** [comment]
Fixed in https://github.com/nray-scanner/nray/commit/e0ff898ea48e7a45a334129b3e6f083534554ba9
